FROM ruby:3.2.1-alpine3.17

RUN apk add --update --no-cache \
  build-base \
  postgresql-dev \
  tzdata

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN gem install bundler && \
    bundle install && \
    rails db:migrate

COPY . .

VOLUME /app

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
