version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile.development
    command: >
      sh -c "bundle exec rails db:create &&
             bundle exec rails db:migrate &&
             bundle exec rails db:seed &&
             bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - .:/app
    ports:
    - "3000:3000"
    depends_on:
    - postgres
    environment:
      RAILS_ENV: development

  pgadmin:
    image: dpage/pgadmin4
    ports:
    - "9876:80"
    depends_on:
    - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@examaple.com
      PGADMIN_DEFAULT_PASSWORD: password

  postgres:
    image: postgres:15.2-alpine
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
